/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedPortalVolunteerRouteImport } from './routes/_authenticated/portal.volunteer'
import { Route as AuthenticatedPortalSupportRouteImport } from './routes/_authenticated/portal.support'
import { Route as AuthenticatedPortalProfileRouteImport } from './routes/_authenticated/portal.profile'
import { Route as AuthenticatedPortalNotificationsRouteImport } from './routes/_authenticated/portal.notifications'
import { Route as AuthenticatedPortalEventsRouteImport } from './routes/_authenticated/portal.events'
import { Route as AuthenticatedPortalDonationsRouteImport } from './routes/_authenticated/portal.donations'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated/portal.documents'
import { Route as AuthenticatedAdminVolunteersRouteImport } from './routes/_authenticated/admin.volunteers'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin.members'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminDonationsRouteImport } from './routes/_authenticated/admin.donations'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPortalVolunteerRoute =
  AuthenticatedPortalVolunteerRouteImport.update({
    id: '/volunteer',
    path: '/volunteer',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalSupportRoute =
  AuthenticatedPortalSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalProfileRoute =
  AuthenticatedPortalProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalNotificationsRoute =
  AuthenticatedPortalNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalEventsRoute =
  AuthenticatedPortalEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDonationsRoute =
  AuthenticatedPortalDonationsRouteImport.update({
    id: '/donations',
    path: '/donations',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDocumentsRoute =
  AuthenticatedPortalDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminVolunteersRoute =
  AuthenticatedAdminVolunteersRouteImport.update({
    id: '/volunteers',
    path: '/volunteers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDonationsRoute =
  AuthenticatedAdminDonationsRouteImport.update({
    id: '/donations',
    path: '/donations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/donations': typeof AuthenticatedPortalDonationsRoute
  '/portal/events': typeof AuthenticatedPortalEventsRoute
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/portal/support': typeof AuthenticatedPortalSupportRoute
  '/portal/volunteer': typeof AuthenticatedPortalVolunteerRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/services': typeof ServicesRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/donations': typeof AuthenticatedPortalDonationsRoute
  '/portal/events': typeof AuthenticatedPortalEventsRoute
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/portal/support': typeof AuthenticatedPortalSupportRoute
  '/portal/volunteer': typeof AuthenticatedPortalVolunteerRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/services': typeof ServicesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/_authenticated/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/portal/donations': typeof AuthenticatedPortalDonationsRoute
  '/_authenticated/portal/events': typeof AuthenticatedPortalEventsRoute
  '/_authenticated/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/_authenticated/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/_authenticated/portal/support': typeof AuthenticatedPortalSupportRoute
  '/_authenticated/portal/volunteer': typeof AuthenticatedPortalVolunteerRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/events'
    | '/services'
    | '/admin'
    | '/portal'
    | '/admin/announcements'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/members'
    | '/admin/staff'
    | '/admin/volunteers'
    | '/portal/documents'
    | '/portal/donations'
    | '/portal/events'
    | '/portal/notifications'
    | '/portal/profile'
    | '/portal/support'
    | '/portal/volunteer'
    | '/admin/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/events'
    | '/services'
    | '/admin/announcements'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/members'
    | '/admin/staff'
    | '/admin/volunteers'
    | '/portal/documents'
    | '/portal/donations'
    | '/portal/events'
    | '/portal/notifications'
    | '/portal/profile'
    | '/portal/support'
    | '/portal/volunteer'
    | '/admin'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/events'
    | '/services'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/donations'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/volunteers'
    | '/_authenticated/portal/documents'
    | '/_authenticated/portal/donations'
    | '/_authenticated/portal/events'
    | '/_authenticated/portal/notifications'
    | '/_authenticated/portal/profile'
    | '/_authenticated/portal/support'
    | '/_authenticated/portal/volunteer'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/portal/volunteer': {
      id: '/_authenticated/portal/volunteer'
      path: '/volunteer'
      fullPath: '/portal/volunteer'
      preLoaderRoute: typeof AuthenticatedPortalVolunteerRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/support': {
      id: '/_authenticated/portal/support'
      path: '/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof AuthenticatedPortalSupportRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/profile': {
      id: '/_authenticated/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof AuthenticatedPortalProfileRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/notifications': {
      id: '/_authenticated/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof AuthenticatedPortalNotificationsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/events': {
      id: '/_authenticated/portal/events'
      path: '/events'
      fullPath: '/portal/events'
      preLoaderRoute: typeof AuthenticatedPortalEventsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/donations': {
      id: '/_authenticated/portal/donations'
      path: '/donations'
      fullPath: '/portal/donations'
      preLoaderRoute: typeof AuthenticatedPortalDonationsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/documents': {
      id: '/_authenticated/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/volunteers': {
      id: '/_authenticated/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AuthenticatedAdminVolunteersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/donations': {
      id: '/_authenticated/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AuthenticatedAdminDonationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminDonationsRoute: typeof AuthenticatedAdminDonationsRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminVolunteersRoute: typeof AuthenticatedAdminVolunteersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminDonationsRoute: AuthenticatedAdminDonationsRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminVolunteersRoute: AuthenticatedAdminVolunteersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalDonationsRoute: typeof AuthenticatedPortalDonationsRoute
  AuthenticatedPortalEventsRoute: typeof AuthenticatedPortalEventsRoute
  AuthenticatedPortalNotificationsRoute: typeof AuthenticatedPortalNotificationsRoute
  AuthenticatedPortalProfileRoute: typeof AuthenticatedPortalProfileRoute
  AuthenticatedPortalSupportRoute: typeof AuthenticatedPortalSupportRoute
  AuthenticatedPortalVolunteerRoute: typeof AuthenticatedPortalVolunteerRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
  AuthenticatedPortalDonationsRoute: AuthenticatedPortalDonationsRoute,
  AuthenticatedPortalEventsRoute: AuthenticatedPortalEventsRoute,
  AuthenticatedPortalNotificationsRoute: AuthenticatedPortalNotificationsRoute,
  AuthenticatedPortalProfileRoute: AuthenticatedPortalProfileRoute,
  AuthenticatedPortalSupportRoute: AuthenticatedPortalSupportRoute,
  AuthenticatedPortalVolunteerRoute: AuthenticatedPortalVolunteerRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
